Update publish script to commit new version number

diff --git a/scripts/publish b/scripts/publish
--- a/scripts/publish
+++ b/scripts/publish
@@ -5,11 +5,6 @@ function die {
     exit 1
 }
 
-git checkout production \
-    && git rebase master \
-    && git push \
-    && git checkout master
-
 read -p "Major, minor, patch? " VERSION_TYPE
 if [[ "$VERSION_TYPE" == "" ]]; then
     exit 1
@@ -17,5 +12,14 @@ fi
 
 npm version "$VERSION_TYPE" || die "Invalid version type: $VERSION_TYPE"
 npm publish
+
+git add package.json \
+    && git commit -m "Update package version" \
+    && git push \
+    && git checkout production \
+    && git rebase master \
+    && git push \
+    && git checkout master \
+    || die "Could not publish changes"
 
 grunt clean build
